# Generated by Django 5.0.3 on 2024-05-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_region_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='area_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(null=True, upload_to='area_img/'),
        ),
        migrations.AddField(
            model_name='region',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
