# Generated by Django 5.0.3 on 2024-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_region_population_compared_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='population_compared_to',
            field=models.DateField(null=True, verbose_name=models.IntegerField(blank=True, null=True)),
        ),
    ]
