# Generated by Django 5.0.3 on 2024-05-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_region_options_region_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterField(
            model_name='region',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Joylash vaqti'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='app.region', verbose_name='Joylashgan hudud'),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(null=True, verbose_name='Aholisi'),
        ),
        migrations.AlterField(
            model_name='region',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Sahifaga chiqarish'),
        ),
    ]
